### ISSUE TITLE
Widgets flicker when scrolling through pages

### ISSUE THREAD

**Issue by ClockGen** [SimpleMobileTools/Simple-Launcher#133]
## Description
When scrolling through pages, widgets from all pages briefly appear on screen.

## App version
5.1.0

## OS info
LineageOS 20 (Android 13)

**Comment by esensar** [comment]
Thank you for reporting these issues @ClockGen 

Do you mind checking out a build with these issues fixed (#129, #131, #132 and this one - #133)?

[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12683143/launcher-core-release.apk.zip)

Just remove `.zip` suffix - I had to add it since GitHub doesn't allow posting `.apk` files. This is a release version, but I made it have a different package so it doesn't force you to uninstall the current one, since it is signed with a different key.

**Comment by ClockGen** [comment]
@esensar Thank you for fixing these bugs so fast. I tested the build and the abovementioned bugs are fixed, I couldn't reproduce any of them. The only breaking bug remains is #130.

**Comment by esensar** [comment]
Thank you for testing!
Yeah, that one is a bit troublesome. I don't want to hack in some fix that could break something else, so it may take some more time
