### ISSUE TITLE
Content of folder on start screen not clickable with widgets in background

### ISSUE THREAD

**Issue by annoying-default-user** [SimpleMobileTools/Simple-Launcher#147]
With the latest version 5.1.1, I have a problem with folders on the start screen. When I open a folder, then nothing happens on tap on apps "laying in front of widgets". The red rectangles in my screenshot are the spaces of the widgets (the upper one is greater then visible), a tap just can open an app outside or in the small space between the widgets. For example, to open Firefox, I've to tap on the lower end of the icon, above the "Firefox".
You can see that the widget is overlaying, if you tap and hold a moment, the context menu for widgets will appear (for resizing and removing).
I'm on a Pixel 6 with latest Version of Android 13.

![Screenshot_20230925-151008](https://github.com/SimpleMobileTools/Simple-Launcher/assets/145995426/038e0aff-d28e-44c7-bac7-41c82618091f)

**Comment by esensar** [comment]
Thank you for reporting this @annoying-default-user 

I have fixed it in #148 and you can confirm it in a custom build right now if you would like. I have added `.zip` suffix to the file since GitHub doesn't allow uploading `.apk` files, so just remove that prefix before trying to install the app.

[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12725224/launcher-core-release.apk.zip)

**Comment by annoying-default-user** [comment]
I can confirm, the fixed version is working, regarding to my bug. Great, thanks for quick response and great Android tools in general 👍
